### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ghost** [UCCEWB/uccewb.github.io#27]
Hi there,

Your link that titles `learn more` on your homepage gives me a 404.  Please fix

**Comment by michael-bateman** [comment]
Hi @gafetest ,

Thank you for pointing this out.  We will try to fix this bug as soon as possible.  In the meantime, you can learn more about our club by visiting https://uccewb.github.io/about/

**Comment by michael-bateman** [comment]
Hi @gafetest ,

The issue has now been fixed.
